/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Aug 09 2022 05:24:23 GMT+0000 (Coordinated Universal Time).
 */

define(['jointjs','css!./styles/PetriNetVisualizerWidget.css'], function (joint) {
    'use strict';

    var WIDGET_CLASS = 'petri-net-visualizer';

    function PetriNetVisualizerWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    }

    PetriNetVisualizerWidget.prototype._initialize = function () {
        console.log( joint );

        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        this._jointPetriNet = new joint.dia.Graph;
        this._jointPaper = new joint.dia.Paper({
            el: this._el,
            width : width,
            height: height,
            model: this._jointPetriNet,
            interactive: false
        });

        // add event calls to elements
        this._jointPaper.on('element:pointerdblclick', function(elementView) {
            const currentElement = elementView.model;
            // console.log(currentElement);
            if (self._webgmePetriNet) {
                // console.log(self._webgmePetriNet.id2state[currentElement.id]);
                self._setCurrentState(self._webgmePetriNet.id2state[currentElement.id]);
            }
        });

        // this._webgmePetriNet = null;        
        // // Create a dummy header
        // this._el.append('<h3>PetriNetVisualizer Events:</h3>');

        // // Registering to events can be done with jQuery (as normal)
        // this._el.on('dblclick', function (event) {
        //     event.stopPropagation();
        //     event.preventDefault();
        //     self.onBackgroundDblClick();
        // });
    };

    PetriNetVisualizerWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // PetriNet manipulating functions called from the controller
    PetriNetVisualizerWidget.prototype.initPetriNet = function (petriNetDescriptor) {
        const self = this;
        console.log(petriNetDescriptor);

        self._webgmePetriNet = petriNetDescriptor;
        self._webgmePetriNet.current = self._webgmePetriNet.init;
        self._jointPetriNet.clear();
        const pn = self._webgmePetriNet;
        pn.id2state = {}; // this dictionary will connect the on-screen id to the state id first add the states
        Object.keys(pn.states).forEach(stateId => {
            let vertex = null;
            if (pn.init === stateId) {
                vertex = new joint.shapes.standard.Circle({
                    position: pn.states[stateId].position,
                    size: { width: 20, height: 20 },
                    attrs: {
                        body: {
                            fill: '#333333',
                            cursor: 'pointer'
                        }
                    }
                });
            } else if (pn.states[stateId].isEnd) {
                vertex = new joint.shapes.standard.Circle({
                    position: pn.states[stateId].position,
                    size: { width: 30, height: 30 },
                    attrs: {
                        body: {
                            fill: '#999999',
                            cursor: 'pointer'
                        }
                    }
                });
            } else {
                vertex = new joint.shapes.standard.Circle({
                    position: pn.states[stateId].position,
                    size: { width: 60, height: 60 },
                    attrs: {
                        label : {
                            text: pn.states[stateId].name,
                            //event: 'element:label:pointerdown',
                            fontWeight: 'bold',
                            //cursor: 'text',
                            //style: {
                            //    userSelect: 'text'
                            //}
                        },
                        body: {
                            strokeWidth: 3,
                            cursor: 'pointer'
                        }
                    }
                });
            }
            vertex.addTo(self._jointPetriNet);
            pn.states[stateId].joint = vertex;
            pn.id2state[vertex.id] = stateId;
        });

        // then create the links
        Object.keys(pn.states).forEach(stateId => {
            const state = pn.states[stateId];
            Object.keys(state.next).forEach(event => {
                state.jointNext = state.jointNext || {};
                const link = new joint.shapes.standard.Link({
                    source: {id: state.joint.id},
                    target: {id: pn.states[state.next[event]].joint.id},
                    attrs: {
                        line: {
                            strokeWidth: 2
                        },
                        wrapper: {
                            cursor: 'default'
                        }
                    },
                    labels: [{
                        position: {
                            distance: 0.5,
                            offset: 0,
                            args: {
                                keepGradient: true,
                                ensureLegibility: true
                            }
                        },
                        attrs: {
                            text: {
                                text: event,
                                fontWeight: 'bold'
                            }
                        }
                    }]
                });
                link.addTo(self._jointPetriNet);
                state.jointNext[event] = link;
            })
        });

        //now refresh the visualization
        self._jointPaper.updateViews();
        self._decoratePetriNet();
    };

    PetriNetVisualizerWidget.prototype.destroyPetriNet = function () {

    };

    PetriNetVisualizerWidget.prototype.fireEvent = function (event) {
        const self = this;
        const current = self._webgmePetriNet.states[self._webgmePetriNet.current];
        const link = current.jointNext[event];
        const linkView = link.findView(self._jointPaper);
        linkView.sendToken(joint.V('circle', { r: 10, fill: 'black' }), {duration:500}, function() {
           self._webgmePetriNet.current = current.next[event];
           self._decoratePetriNet();
        });
    };

    PetriNetVisualizerWidget.prototype.resetPetriNet = function () {
        this._webgmePetriNet.current = this._webgmePetriNet.init;
        this._decoratePetriNet();
    };

    PetriNetVisualizerWidget.prototype._decoratePetriNet = function() {
        const pn = this._webgmePetriNet;
        Object.keys(pn.states).forEach(stateId => {
            pn.states[stateId].joint.attr('body/stroke', '#333333');
        });
        pn.states[pn.current].joint.attr('body/stroke', 'blue');
        pn.setFireableEvents(Object.keys(pn.states[pn.current].next));
    };

    PetriNetVisualizerWidget.prototype._setCurrentState = function(newCurrent) {
        this._webgmePetriNet.current = newCurrent;
        this._decoratePetriNet();
    };
    

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    PetriNetVisualizerWidget.prototype.destroy = function () {
    };

    PetriNetVisualizerWidget.prototype.onActivate = function () {
        this._logger.debug('PetriNetVisualizerWidget has been activated');
    };

    PetriNetVisualizerWidget.prototype.onDeactivate = function () {
        this._logger.debug('PetriNetVisualizerWidget has been deactivated');
    };

    PetriNetVisualizerWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    PetriNetVisualizerWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };


    return PetriNetVisualizerWidget;

    // // Adding/Removing/Updating items
    // PetriNetVisualizerWidget.prototype.addNode = function (desc) {
    //     if (desc) {
    //         // Add node to a table of nodes
    //         var node = document.createElement('div'),
    //             label = 'children';

    //         if (desc.childrenIds.length === 1) {
    //             label = 'child';
    //         }

    //         this.nodes[desc.id] = desc;
    //         node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' +
    //             desc.childrenIds.length + ' ' + label + '.';

    //         this._el.append(node);
    //         node.onclick = this.onNodeClick.bind(this, desc.id);
    //     }
    // };

    // PetriNetVisualizerWidget.prototype.removeNode = function (gmeId) {
    //     var desc = this.nodes[gmeId];
    //     this._el.append('<div>Removing node "' + desc.name + '"</div>');
    //     delete this.nodes[gmeId];
    // };

    // PetriNetVisualizerWidget.prototype.updateNode = function (desc) {
    //     if (desc) {
    //         this._logger.debug('Updating node:', desc);
    //         this._el.append('<div>Updating node "' + desc.name + '"</div>');
    //     }
    // };

    // /* * * * * * * * Visualizer event handlers * * * * * * * */

    // PetriNetVisualizerWidget.prototype.onNodeClick = function (/*id*/) {
    //     // This currently changes the active node to the given id and
    //     // this is overridden in the controller.
    // };

    // PetriNetVisualizerWidget.prototype.onBackgroundDblClick = function () {
    //     this._el.append('<div>Background was double-clicked!!</div>');
    // };

    // /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    // PetriNetVisualizerWidget.prototype.destroy = function () {
    // };

    // PetriNetVisualizerWidget.prototype.onActivate = function () {
    //     this._logger.debug('PetriNetVisualizerWidget has been activated');
    // };

    // PetriNetVisualizerWidget.prototype.onDeactivate = function () {
    //     this._logger.debug('PetriNetVisualizerWidget has been deactivated');
    // };

    // return PetriNetVisualizerWidget;
});
